<?php
$this->headTitle('Zarządzanie cytatami');

$this->mainMenu()->setActiveItemId('quotes');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Cytaty'=>$this->url('quotes'),
            ]);
?>

<h3 class="app-content-title">Cytaty</h3>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<div id="quote-list">
<h6 class="app-content-subtitle">Lista cytatów</h6>
<p>
<a class="btn btn-secondary btn-sm" href="
    <?= $this->url('quotes', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Dodaj cytat
</a>
</p>

<table class="table table-striped small table-responsive app-data-table">

   <thead>
        <!--<th>ID</th>-->
        <th>Autor</th>
        <th>Cytat</th>
        <th class='nosort noorder'>Akcje</th>
    </thead>
    <tbody>
    <?php foreach ($quotes as $quote): ?>

    <tr>
        <td>
                <?= $this->escapeHtml($quote->getAuthor()); ?>
        </td>
        <td>
          <!--<a href="<?= $this->url('quotes', ['action'=>'view', 'id'=>$quote->getId()]); ?>">-->
            <?= $this->escapeHtml($quote->getQuote()); ?></a>
            <!--</a>-->
        </td>
        <td>
            <nobr>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('quotes',
                    ['action'=>'edit', 'id'=>$quote->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edytuj
            </a>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('quotes',
                    ['action'=>'delete', 'id'=>$quote->getId()]); ?>" onclick="return confirm ('Czy na pewno chcesz usunąć ten rekord?')">
                <span class="glyphicon glyphicon-remove"></span> Usuń
            </a>
          </nobr>
        </td>
    </tr>

    <?php endforeach; ?>
</tbody>
</table>
</div>
