<?php
$this->headTitle('Zarządzanie książkami');

$this->mainMenu()->setActiveItemId('quotes');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Książki'=>$this->url('books'),
            ]);
?>

<h3 class="app-content-title">Zarządzanie cytatami</h3>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-secondary btn-sm" href="
    <?= $this->url('books', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Dodaj Książkę
</a>
</p>

<table class="table table-striped small table-responsive app-data-table">

   <thead>
        <!--<th>ID</th>-->
        <th>Autor</th>
        <th>Tytuł</th>
        <th>Akcje</th>
    </thead>
    <tbody>
    <?php foreach ($publications as $publication): ?>

    <tr>
        <td>
                <?= $this->escapeHtml($publication->getAuthor()); ?>
        </td>
        <td>
          <!--<a href="<?= $this->url('books', ['action'=>'view', 'id'=>$publication->getId()]); ?>">-->
            <?= $this->escapeHtml($publication->getTitle()); ?></a>
            <!--</a>-->
        </td>
        <td>
            <nobr>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('books',
                    ['action'=>'edit', 'id'=>$publication->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edytuj
            </a>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('books',
                    ['action'=>'delete', 'id'=>$publication->getId()]); ?>" onclick="return confirm ('Czy na pewno chcesz usunąć ten rekord?')">
                <span class="glyphicon glyphicon-remove"></span> Usuń
            </a>
          </nobr>
        </td>
    </tr>

    <?php endforeach; ?>
</tbody>
</table>
