<?php
$this->headTitle('Zmiana hasła');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Użytkownicy'=>$this->url('users'),
            'Zmiana hasła'=>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
            ]);

$form->get('old_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'wpisz stare hasło'
    ]);

$form->get('new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'wpisz nowe hasło'
    ]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'powtórz nowe hasło'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary btn-sm']);

$form->prepare();
?>

<div class="app-content-title">
  <h3>Zmień hasło użytkownika</h3>
  <h6><?= $this->escapeHtml($user->getEmail()) ?></h6>
</div>


<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('old_password')); ?>
            <?= $this->formElement($form->get('old_password')); ?>
            <?= $this->formElementErrors($form->get('old_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
