<?php
$this->headTitle('Edycja Użytkownika');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Użytkownicy'=>$this->url('users'),
            'Edycja'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
            ]);

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('roles')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary btn-sm'])
        ->setValue('Zapisz');

$form->prepare();
?>

<div class="app-content-title">
  <h3>Edycja użytkownika</h3>
  <h6><?= $this->escapeHtml($user->getEmail()) ?></h6>
</div>


<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('roles')); ?>
            <?= $this->formElement($form->get('roles')); ?>
            <?= $this->formElementErrors($form->get('roles')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElementErrors($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
