<?php
$this->headTitle('Zarządzanie użytkownikami');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Użytkownicy'=>$this->url('users'),
            ]);
?>

<h3 class="app-content-title">Zarządzanie użytkownikami</h3>

<p>
<a class="btn btn-secondary btn-sm" href="
    <?= $this->url('users', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Dodaj użytkownika
</a>
</p>

<table class="table table-striped small table-responsive app-data-table">

   <thead>
        <!--<th>ID</th>-->
        <th>Nazwa</th>
        <th>E-mail</th>
        <th>Role</th>
        <!--<th>Utworzony</th>-->
        <th>Status</th>
        <th>Akcje</th>
    </thead>
    <tbody>
    <?php foreach ($users as $user): ?>

    <tr>
        <!--<td><?= $this->escapeHtml($user->getId()); ?></td>-->
        <td>
            <?= $this->escapeHtml($user->getFullName()); ?></a>
        </td>
        <td>
            <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getEmail()); ?>
            </a>
        </td>
        <td>
            <?= $this->escapeHtml($user->getRolesAsString()); ?></a>
        </td>
        <!--<td><nobr><?= $this->escapeHtml($user->getDateCreated()); ?></nobr></td>-->
        <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
        <td>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('users',
                    ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edytuj
            </a>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('users',
                    ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> Zmień hasło
            </a>
        </td>
    </tr>

    <?php endforeach; ?>
</tbody>
</table>
