<?php
$this->headTitle('Dziękujemy');
?>

<div class="row">
<div class="col-md-offset-4 col-md-5">
<h3 class="app-content-title">Resetowanie hasła</h3>

<?php if ($id=='sent'): ?>
<p>
    Instrukcje dotyczące resetowania hasła zostały wysłane na Twój adres E-mail.
</p>
<?php elseif ($id=='invalid-email'): ?>
<p>
    Nie odnaleziono użytkownika o podanym adresie E-mail lub użytkownik jest nieaktywny.
</p>
<?php elseif ($id=='set'): ?>
<p>
    Twoje nowe hasło zostało ustawione poprawnie.
</p>
<p>
    Powrót do <a href="<?= $this->url('login'); ?>">login page</a>.
</p>
<?php elseif ($id=='failed'): ?>

    Nieprawidłowy kod lub kod wygasł. Ponów próbę
    <a href="<?= $this->url('reset-password') ?>">here</a> and try reset your password again.
</p>
<?php endif; ?>
</div>
</div>
