<?php
$this->headTitle('Reset hasła');

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Adres Email'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-small btn-primary'
    ]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h3>Reset hasła</h3>

        <p>Wpisz swój e-mail poniżej aby zresetować hasło</p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint">Przepisz kod z obrazka.</p>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
