<?php
$this->headTitle('Ustawianie nowego hasła');

$form->get('new_password')->setAttributes(array(
    'class'=>'form-control',
    'placeholder'=>'wpisz nowe hasło'
    ));
$form->get('confirm_new_password')->setAttributes(array(
    'class'=>'form-control',
    'placeholder'=>'powtórz nowe hasło'
    ));
$form->get('submit')->setAttributes(array(
    'class'=>'btn btn-primary btn-sm'
    ));
$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h3 class="app-content-title">Ustawianie nowego hasła</h3>

        <p>wpisz swoje nowe hasło poniżej</p>

        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
