<?php
$this->headTitle('Podgląd użytkownika');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Użytkownicy'=>$this->url('users'),
            'Podgląd'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h3>Podgląd użytkownika <?= $this->escapeHtml($user->getEmail()) ?></h3>

<p>
    <a class="btn btn-secondary btn-sm" href="<?= $this->url('users',
            ['action'=>'edit', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Edytuj
    </a>
    <a class="btn btn-secondary btn-sm" href="<?= $this->url('users',
            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-asterisk"></span> Zmień hasło
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered small table-responsive">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>Nazwa:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Utworzony:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
            <tr>
                <th>Role:</th>
                <td><?= $this->escapeHtml($user->getRolesAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>
