<?php
$this->headTitle('Dodawanie roli');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Role'=>$this->url('roles'),
            'Dodawanie'=>$this->url('roles', ['action'=>'add'])
            ]);

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'wpisz nazwę roli'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'wpisz opis roli'
    ]);

$form->get('inherit_roles')->setAttributes([
    'class'=>'form-control',
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary btn-sm']);

$form->prepare();
?>

<h3>Dodawanie roli</h3>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('inherit_roles')); ?>
            <?= $this->formElement($form->get('inherit_roles')); ?>
            <?= $this->formElementErrors($form->get('inherit_roles')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
