<?php
$this->headTitle('Edycja uprawnień roli');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Role'=>$this->url('roles'),
            'Edycja'=>$this->url('roles', ['action'=>'edit', 'id'=>$role->getId()])
            ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary btn-sm'])
        ->setValue('Zapisz');

$form->prepare();
?>

<h3>Edycja uprawnień roli <?= $this->escapeHtml($role->getName()) ?></h3>

<div class="row">
    <div class="col-md-8">
        <?= $this->form()->openTag($form); ?>
        <table class="table table-striped table-bordered small table-responsive">
            <tr>
                <th>Nazwa uprawnienia</th>
                <th>Opis uprawnienia</th>
            </tr>
            <?php foreach ($allPermissions as $permission):
                $element = $form->get('permissions')->get($permission->getName());
            ?>
            <tr>
                <td>
                    <div class="checkbox">
                        <label><input type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>"
                                      value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                                      <?php if ($element->isChecked()) echo 'checked'?>
                                      <?php if ($element->getAttribute('disabled')) echo 'disabled'?>>
                            <?= $this->escapeHtml($element->getLabel()) ?>
                        </label>
                        <?= $this->formElementErrors($element); ?>
                    </div>
                </td>
                <td>
                    <?= $this->escapeHtml($permission->getDescription()) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">





    </div>
</div>
