<?php
$this->headTitle('Edycja roli');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Role'=>$this->url('roles'),
            'Edycja' => $this->url('roles', ['action'=>'edit', 'id'=>$role->getId()])
            ]);

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'wpisz nazwę roli'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'wpisz opis roli'
    ]);

$form->get('inherit_roles')->setAttributes([
    'class'=>'form-control',
    ]);


$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary btn-sm'])
        ->setValue('Zapisz');

$form->prepare();
?>

<div class="app-content-title">
  <h3>Edycja roli</h3>

</div>
<h6 class="app-content-subtitle">Edycja roli <?= $this->escapeHtml($role->getName()) ?></h6>
<p>
<a class="btn btn-secondary btn-sm" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">
  <span class="glyphicon glyphicon-check"></span> Edytuj uprawnienia
</a>
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('inherit_roles')); ?>
            <?= $this->formElement($form->get('inherit_roles')); ?>
            <?= $this->formElementErrors($form->get('inherit_roles')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
