<?php
$this->headTitle('Zarządzanie rolami');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Role'=>$this->url('roles'),
            ]);
?>

<h3 class="app-content-title">Zarządzanie rolami</h3>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-secondary btn-sm" href="
    <?= $this->url('roles', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Dodaj rolę
</a>
</p>

<table class="table table-striped small table-responsive app-data-table">

   <thead>
        <!--<th>ID</th>-->
        <th>Rola</th>
        <th>Opis</th>
        <!--<th>Utworzono</th>-->
        <th>Akcje</th>
    </thead>
    <tbody>
    <?php foreach ($roles as $role): ?>

    <tr>
        <!--<td><?= $this->escapeHtml($role->getId()); ?></td>-->
        <td>
            <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                <?= $this->escapeHtml($role->getName()); ?>
            </a>
        </td>
        <td><?= $this->escapeHtml($role->getDescription()); ?></a>
        </td>
        <!--<td><nobr><?= $this->escapeHtml($role->getDateCreated()); ?></nobr></td>-->
        <td>
            </nobr>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('roles',
                    ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edytuj
            </a>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('roles',
                    ['action'=>'delete', 'id'=>$role->getId()]); ?>" onclick="return confirm ('Czy na pewno chcesz usunąć ten rekord?')">
                <span class="glyphicon glyphicon-remove"></span> Usuń
            </a>
            </nobr>
        </td>
    </tr>

    <?php endforeach; ?>
</tbody>
</table>
