<?php
$this->headTitle('Podgląd roli');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Role'=>$this->url('roles'),
            'Podgląd'=> $this->url('roles', ['action'=>'view', 'id'=>$role->getId()])
            ]);
?>

<div class="app-content-title">
  <h3>Podgląd roli</h3>
  <h6><?= $this->escapeHtml($role->getName()) ?></h6>
</div>



<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-secondary btn-sm" href="<?= $this->url('roles',
                    ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edytuj rolę
</a>
</p>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered small table-responsive">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($role->getId()) ?></th>
            </tr>
            <tr>
                <th>Nazwa roli:</th>
                <td><?= $this->escapeHtml($role->getName()) ?></th>
            </tr>
            <tr>
                <th>Opis roli:</th>
                <td><?= $this->escapeHtml($role->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Utworzono:</th>
                <td><?= $this->escapeHtml($role->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>

<h3>Uprawnienia</h3>

<p>
<a class="btn btn-secondary btn-sm" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">
  <span class="glyphicon glyphicon-check"></span> Edytuj uprawnienia
</a>
</p>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Nazwa uprawnienia</th>
                <th>Opis uprawnienia</th>
            </tr>
            <?php foreach($allPermissions as $permission): ?>
            <tr>
                <td>
                    <input type="checkbox" disabled <?php if (isset($effectivePermissions[$permission->getName()])) echo 'checked'; ?>>
                    <?= $this->escapeHtml($permission->getName()) ?>
                    <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()]=='inherited'): ?>
                    <em>(inherited)</em>
                    <?php endif; ?>
                </td>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
