<?php
$this->headTitle('Edycja uprawnienia');

$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Uprawnienia'=>$this->url('permissions'),
            'Edycja'=>$this->url('permissions', ['action'=>'edit', 'id'=>$permission->getId()])
            ]);

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'wpisz nazwę'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'wpisz opis'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary btn-sm'])
        ->setValue('Zapisz');

$form->prepare();
?>

<h3 class="app-content-title">Uprawnienia</h3>
<h6 class="app-content-subtitle">Edycja uprawnienia</h6>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
