<?php
$this->headTitle('Zarządzanie uprawnieniami');

$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Uprawnienia'=>$this->url('permissions'),
            ]);
?>

<h3 class="app-content-title">Zarządzanie uprawnieniami</h3>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-secondary btn-sm" href="
    <?= $this->url('permissions', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Dodaj uprawnienie
</a>
</p>

<table class="table table-striped small table-responsive app-data-table">

   <thead>
        <!--<th>ID</th>-->
        <th>Uprawnienie</th>
        <th>Opis</th>
        <!--<th>Date Created</th>-->
        <th>Akcje</th>
    </thead>
    <tbody>
    <?php foreach ($permissions as $permission): ?>

    <tr>
        <!--<td><?= $this->escapeHtml($permission->getId()); ?></td>-->
        <td>
            <a href="<?= $this->url('permissions', ['action'=>'view', 'id'=>$permission->getId()]); ?>">
                <?= $this->escapeHtml($permission->getName()); ?>
            </a>
        </td>
        <td><?= $this->escapeHtml($permission->getDescription()); ?></a>
        </td>
        <!--<td><nobr><?= $this->escapeHtml($permission->getDateCreated()); ?></nobr></td>-->
        <td>
            <nobr>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('permissions',
                    ['action'=>'edit', 'id'=>$permission->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edytuj
            </a>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('permissions',
                    ['action'=>'delete', 'id'=>$permission->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Usuń
            </a>
            </nobr>
        </td>
    </tr>

    <?php endforeach; ?>
</tbody>
</table>
