<?php
$this->headTitle('Podgląd uprawnienia');

$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Uprawnienia'=>$this->url('permissions'),
            'Podgląd'=>$this->url('permissions', ['action'=>'view', 'id'=>$permission->getId()])
            ]);
?>


<h3>Podgląd uprawnienia</h3>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered small table-responsive">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($permission->getId()) ?></th>
            </tr>
            <tr>
                <th>Nazwa:</th>
                <td><?= $this->escapeHtml($permission->getName()) ?></th>
            </tr>
            <tr>
                <th>Opis:</th>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Utworzono:</th>
                <td><?= $this->escapeHtml($permission->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>
