<?php
$this->headTitle('Zarządzanie krwiodawstwem');

$this->mainMenu()->setActiveItemId('blooddonation');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Krwiodawstwo'=>$this->url('blooddonation'),
            ]);
?>

<h3 class="app-content-title">Krwiodawstwo</h3>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="bookmarks-bar">
  <ul class="nav nav-pills">
  <li class="nav-item">
    <button id='blood-donation-dashboard-btn' class="btn btn-secondary" aria-current="page" href="#">Podsumowanie</button>
  </li>
  <li class="nav-item">
      <button id='blood-donation-list-btn' class="btn btn-light" href="#" tabindex="-1" aria-disabled="true">Lista donacji</button>
  </li>
</ul>
</div>
<div id="blood-donation-dashboard">
<h4 class="app-content-subtitle">Podsumowanie</h4>
<div class="row">
<div class="col-xl-4 col-lg-6 px-3 blood-donation-stats-section">
  <h6 class="stats-subtitle">
    Statystyki
  </h6>
  <table id="blood-donation-stats-tab" class="table table-striped small table-responsive">
      <tr>
        <th>Oddana krew</th>
        <td>
            <?= $this->escapeHtml($bloodDonationStats['bloodSum']); ?> ml
        </td>
      </tr>
      <tr>
        <th>Data ostatniej donacji</th>
        <td>
          <?= substr($this->escapeHtml($bloodDonationStats['lastBloodDonationDate']),0,10); ?>
        </td>
      </tr>
      <tr>
        <th>Data pierwszej donacji</th>
        <td>
          <?= substr($this->escapeHtml($bloodDonationStats['firstBloodDonationDate']),0,10); ?>
        </td>
      </tr>
      <tr>
        <th>Skuteczne donacje</th>
        <td>
          <?= $this->escapeHtml($bloodDonationStats['bloodDonationCount']); ?>
        </td>
      </tr>
      <tr>
        <th>Próby donacji</th>
        <td>
          <?= $this->escapeHtml($bloodDonationStats['bloodDonationAttemptsCount']); ?>
        </td>
      </tr>
  </table>
</div>
<div class="col-xl-4 col-lg-6 px-3 blood-donation-stats-section">
  <h6 class="stats-subtitle">
    6 ostatnich donacji
  </h6>
  <canvas id="lastSixBloodDonationsChart" width="80" height="50"></canvas>
</div>

<div class="col-xl-4 col-lg-6 px-3 blood-donation-stats-section">
  <h6 class="stats-subtitle">
    Najbliższa donacja
  </h6>
  <table id="blood-donation-next-tab" class="table table-striped small table-responsive">
      <tr>
        <th>Planowana data</th>
        <td>
          <?= substr($this->escapeHtml($bloodDonationStats['nextPlannedDonationDate']),0,10); ?>
        </td>
      </tr>
      <tr>
        <th>Możliwa data</th>
        <td>
            <?= $this->escapeHtml($bloodDonationStats['nextPossibleDonationDate']); ?>
        </td>
      </tr>
      <tr>
        <th>Warunek 8 tygodni <?php echo $bloodDonationStats['eightWeeksConditionStringElements'][0]; ?></th>
        <td class="<?php echo $bloodDonationStats['eightWeeksConditionStringElements'][1] ?>">
          <?= substr($this->escapeHtml($bloodDonationStats['eightWeeksConditionDate']),0,10); ?>
        </td>
      </tr>
      <tr>
        <th>Warunek 6 donacji w roku <?php echo $bloodDonationStats['sixDonationsPerYearConditionStringElements'][0]; ?></th>
        <td class="<?php echo $bloodDonationStats['sixDonationsPerYearConditionStringElements'][1]; ?>">
          <?= substr($this->escapeHtml($bloodDonationStats['sixDonationsPerYearConditionDate']),0,10); ?>
        </td>
      </tr>
  </table>
</div>
</div>
</div>
<div id="blood-donation-list">
<h4 class="app-content-subtitle">Lista donacji</h4>
<p>
<a class="btn btn-secondary btn-sm" href="
    <?= $this->url('blooddonation', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Dodaj donację
</a>
</p>

<table id="blood-donation-table" class="table table-striped small table-responsive blood-donation-table">

   <thead>
        <!--<th>ID</th>-->
        <th>Data</th>
        <th>Miejsce</th>
        <th>Status</th>
        <th>Karencja do</th>
        <th>Ilość (ml)</th>
        <th class='nosort noorder'>Akcje</th>
    </thead>
    <tbody>
    <?php foreach ($bloodDonations as $bloodDonation): ?>

    <tr>
        <td>
            <?=substr($this->escapeHtml($bloodDonation->getEventDate()),0,10);?>
        </td>
        <td>
            <?=$this->escapeHtml($bloodDonation->getPlace()); ?>
        </td>
        <td>
            <?php echo $bloodDonation->getDonationInfoIcons(); ?>
        </td>
        <td>
            <?=$this->escapeHtml($bloodDonation->getBanDateTo()); ?>
        </td>
        <td>
            <?=$this->escapeHtml($bloodDonation->getDonatedBloodAmount()); ?>
        </td>
        <td>
            <nobr>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('blooddonation',
                    ['action'=>'edit', 'id'=>$bloodDonation->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edytuj
            </a>
            <a class="btn btn-secondary btn-sm" href="<?= $this->url('blooddonation',
                    ['action'=>'delete', 'id'=>$bloodDonation->getId()]); ?>" onclick="return confirm ('Czy na pewno chcesz usunąć ten rekord?')">
                <span class="glyphicon glyphicon-remove"></span> Usuń
            </a>
          </nobr>
        </td>
    </tr>

    <?php endforeach; ?>
</div>

<?= $this->inlineScript()
      ->prependFile($this->basePath('js/chart.js-3.8.2/package/dist/chart.min.js'))
      ->prependFile($this->basePath('js/blooddonation.js'))
?>

<script>
var lastSixBloodDonationsDates =  <?php echo json_encode($bloodDonationStats['lastSixBloodDonationsDates']); ?>;
var lastSixBloodDonationsAmounts = <?php echo json_encode($bloodDonationStats['lastSixBloodDonationsAmounts']); ?>;
</script>

</tbody>
</table>
